// PLACEHOLDER - the real per-app types are generated by the running app.
// Pull the live types any time from your running server with:
//   curl http://localhost:8080/_internal/bm.d.ts > src/bm.d.ts

// SDK surface (matches /_internal/bm.js). Full per-app types land
// on first push.
export interface User { id: number; email: string; first_name?: string; last_name?: string; role: string; verified: number; }
export interface ApiResult<T = unknown> { ok: boolean; status: number; data: T | null; }
export type ChangeEvent<T = Record<string, unknown>> =
  | { action: 'insert' | 'update'; table: string; id: number; row: T }
  | { action: 'delete'; table: string; id: number }
  | { action: 'refresh'; table: '' };

export interface TableClient<Row = Record<string, unknown>> {
  list(opts?: { limit?: number; offset?: number; q?: string }): Promise<Row[]>;
  get(id: number | string): Promise<Row>;
  create(body: Partial<Row>): Promise<Row>;
  update(id: number | string, body: Partial<Row>): Promise<Row>;
  delete(id: number | string): Promise<void>;
}

export const api: {
  get<T = any>(path: string): Promise<T>;
  post<T = any>(path: string, body?: unknown): Promise<T>;
  patch<T = any>(path: string, body?: unknown): Promise<T>;
  delete(path: string): Promise<void>;
};
export const auth: {
  me(): Promise<User | null>;
  signOut(): Promise<void>;
  refreshMe(): Promise<User | null>;
};
export const users: {
  list(opts?: { limit?: number; offset?: number }): Promise<User[]>;
  get(id: number): Promise<User>;
};
export function table<R = Record<string, unknown>>(name: string): TableClient<R>;
export function live<T = Record<string, unknown>>(table: string, cb: (ev: ChangeEvent<T>) => void): () => void;
export function room(name: string): {
  on(kind: string, fn: (payload: any, from: number) => void): any;
  send(payload: any): void;
  leave(): void;
};

declare const bm: {
  api: typeof api;
  auth: typeof auth;
  users: typeof users;
  table: typeof table;
  live: typeof live;
  room: typeof room;
};
export default bm;
